flight_locations: [
    "Sofia",
    "Eindhoven",
    "Paris",
    "Rome",
    "Lisbon",
    "Bucharest",
    "Budapest",
    "Copenhagen",
    "Amsterdam",
    "Berlin"
]
start_date: 11
end_date: 15
WORKERS: 6