flight_locations: [
    "Sofia",
    "Eindhoven",
    "Paris",
    "Rome",
    "Lisbon",
    "Bucharest",
    "Budapest",
    "Copenhagen",
    "Amsterdam",
    "Berlin",
    "Copenhagen",
    "Luxembourg",
    "London",
    "Dublin",
    "Vienna"
]
start_date: 12
end_date: 31
WORKERS: 7
